# Generated by Django 3.0.4 on 2020-07-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0016_auto_20200719_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='station',
        ),
    ]
